project_name: hooksy

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Version }}-next'
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*(feat)[(\\w)]*.*$"
    - title: Bug Fixes
      regexp: "^.*(fix)[(\\w)]*.*$"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: govindrajvanshi
    name: hooksy
